"""add email verification columns to users

Revision ID: 3d8f5481af09
Revises: af4894d1f431
Create Date: 2026-07-31 09:38:15.800359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d8f5481af09'
down_revision: Union[str, None] = 'af4894d1f431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('verification_code_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('verification_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('verification_attempts', sa.Integer(), server_default='0', nullable=False))
    # 既存ユーザー（初期代表2件）は確認済みとして扱う。
    # そうしないと D-012 の未確認チェックによりログイン不能になるため。
    op.execute("UPDATE users SET email_verified_at = NOW() WHERE email_verified_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_attempts')
    op.drop_column('users', 'verification_expires_at')
    op.drop_column('users', 'verification_code_hash')
    op.drop_column('users', 'email_verified_at')
    # ### end Alembic commands ###
