"""create initial 8 tables

Revision ID: af4894d1f431
Revises: 
Create Date: 2026-07-09 08:32:35.814130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'af4894d1f431'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lottery_settings',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('rescue_alpha', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IN ('male', 'female')", name='ck_lottery_settings_gender'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gender')
    )
    op.create_table('practice_months',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('vote_starts_at', sa.DateTime(), nullable=False),
    sa.Column('vote_ends_at', sa.DateTime(), nullable=False),
    sa.Column('grade2_ratio', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IN ('male', 'female')", name='ck_practice_months_gender'),
    sa.CheckConstraint("status IN ('draft', 'voting', 'closed', 'drawn', 'published')", name='ck_practice_months_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_month', 'gender', name='uq_practice_months_ym_gender')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('faculty_department', sa.String(length=100), nullable=False),
    sa.Column('student_number', sa.String(length=30), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IN ('male', 'female')", name='ck_users_gender'),
    sa.CheckConstraint("role IN ('member', 'representative')", name='ck_users_role'),
    sa.CheckConstraint('grade BETWEEN 1 AND 3', name='ck_users_grade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_gender_grade', 'users', ['gender', 'grade'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('lottery_executions',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('practice_month_id', sa.String(length=30), nullable=False),
    sa.Column('executed_by', sa.String(length=30), nullable=False),
    sa.Column('random_seed', sa.BigInteger(), nullable=False),
    sa.Column('grade2_ratio', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('settings_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['practice_month_id'], ['practice_months.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lottery_executions_month_active', 'lottery_executions', ['practice_month_id', 'is_active'], unique=False)
    op.create_table('monthly_member_results',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('practice_month_id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('votes_count', sa.Integer(), nullable=False),
    sa.Column('wins_count', sa.Integer(), nullable=False),
    sa.Column('losses_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_month_id'], ['practice_months.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_month_id', 'user_id', name='uq_mmr_month_user')
    )
    op.create_table('practices',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('practice_month_id', sa.String(length=30), nullable=False),
    sa.Column('practice_date', sa.Date(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_practices_capacity'),
    sa.ForeignKeyConstraint(['practice_month_id'], ['practice_months.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_practices_month_date', 'practices', ['practice_month_id', 'practice_date'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('practice_id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('lottery_execution_id', sa.String(length=30), nullable=True),
    sa.Column('assigned_via', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("assigned_via IN ('manager', 'grade3', 'guaranteed', 'distribution', 'overflow', 'manual')", name='ck_assignments_via'),
    sa.ForeignKeyConstraint(['lottery_execution_id'], ['lottery_executions.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_user', 'assignments', ['user_id'], unique=False)
    op.create_index('uq_assignments_practice_user_active', 'assignments', ['practice_id', 'user_id'], unique=True, postgresql_where='is_deleted = false')
    op.create_table('votes',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('practice_id', sa.String(length=30), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'practice_id', name='uq_votes_user_practice')
    )
    op.create_index('ix_votes_practice', 'votes', ['practice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_votes_practice', table_name='votes')
    op.drop_table('votes')
    op.drop_index('uq_assignments_practice_user_active', table_name='assignments', postgresql_where='is_deleted = false')
    op.drop_index('ix_assignments_user', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_practices_month_date', table_name='practices')
    op.drop_table('practices')
    op.drop_table('monthly_member_results')
    op.drop_index('ix_lottery_executions_month_active', table_name='lottery_executions')
    op.drop_table('lottery_executions')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_gender_grade', table_name='users')
    op.drop_table('users')
    op.drop_table('practice_months')
    op.drop_table('lottery_settings')
    # ### end Alembic commands ###
