"""add per-grade quotas to practices

Revision ID: d4abe0316512
Revises: 35596e50910f
Create Date: 2026-08-02 10:41:18.610689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4abe0316512'
down_revision: Union[str, None] = '35596e50910f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lottery_executions', 'grade2_ratio',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True)
    op.add_column('practices', sa.Column('quota_grade1', sa.Integer(), nullable=True))
    op.add_column('practices', sa.Column('quota_grade2', sa.Integer(), nullable=True))
    op.add_column('practices', sa.Column('quota_grade3', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practices', 'quota_grade3')
    op.drop_column('practices', 'quota_grade2')
    op.drop_column('practices', 'quota_grade1')
    op.alter_column('lottery_executions', 'grade2_ratio',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False)
    # ### end Alembic commands ###
