"""add line_user_id and drop personal info columns

Revision ID: f82ebb281c70
Revises: d4abe0316512
Create Date: 2026-08-06 03:11:56.420186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f82ebb281c70'
down_revision: Union[str, None] = 'd4abe0316512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('line_user_id', sa.String(length=50), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint('uq_users_line_user_id', 'users', ['line_user_id'])
    op.drop_column('users', 'student_number')
    op.drop_column('users', 'faculty_department')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('faculty_department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('student_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint('uq_users_line_user_id', 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'line_user_id')
    # ### end Alembic commands ###
